const mongoose = require('mongoose');
const Topic = require('../models/Topic');
require('dotenv').config({ path: '../.env' });

const problem = {
    title: '389. Find the Difference',
    level: 'Beginner',
    difficulty: 'Easy',
    subject: 'DSA',
    topicGroup: 'Sorting',
    isCoreCS: true,
    lessonType: 'practice',
    content: {
        description: "Given two strings where t is a shuffled copy of s with one extra character, find the added character.",
        problemStatement: [
            '## 389. Find the Difference',
            '',
            'You are given two strings `s` and `t`.',
            '',
            'String `t` is generated by random shuffling string `s` and then add one more letter at a random position.',
            '',
            'Return the letter that was added to `t`.',
            '',
            '---',
            '',
            '### Example 1:',
            '**Input:** s = "abcd", t = "abcde"',
            '**Output:** "e"',
            '**Explanation:** \'e\' is the letter that was added.',
            '',
            '### Example 2:',
            '**Input:** s = "", t = "y"',
            '**Output:** "y"',
            '',
            '---',
            '',
            '### Constraints:',
            '* `0 <= s.length <= 1000`',
            '* `t.length == s.length + 1`',
            '* `s` and `t` consist of lowercase English letters.'
        ].join('\n'),
        starterCode: [
            '/**',
            ' * @param {string} s',
            ' * @param {string} t',
            ' * @return {character}',
            ' */',
            'var findTheDifference = function(s, t) {',
            '    ',
            '};'
        ].join('\n'),
        testCases: [
            {
                input: '"abcd", "abcde"',
                expected: '"e"',
                description: 'Added letter at the end.'
            },
            {
                input: '"", "y"',
                expected: '"y"',
                description: 'Empty starting string.'
            }
        ],
        tags: ['Hash Table', 'String', 'Bit Manipulation', 'Sorting'],
        hints: [
            "You can use a Hash Table to map characters in `s` and their frequencies, and then compare it with `t`.",
            "Alternatively, use bit manipulation by XORing all characters from both strings. The final result will be the extra character code.",
            "Sorting both strings and searching for the first difference is another easy approach."
        ]
    }
};

mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/develevate').then(async () => {
    console.log('Connected to MongoDB');
    const existing = await Topic.findOne({ title: problem.title, subject: 'DSA' });
    if (existing) {
        await Topic.findByIdAndUpdate(existing._id, problem);
        console.log('Updated:', problem.title);
    } else {
        await new Topic(problem).save();
        console.log('Added:', problem.title);
    }
    mongoose.connection.close();
}).catch(e => { console.error(e); process.exit(1); });
