const mongoose = require('mongoose');
const Topic = require('../models/Topic');
require('dotenv').config({ path: '../.env' });

const problems = [
    {
        title: '290. Word Pattern',
        level: 'Beginner',
        difficulty: 'Easy',
        subject: 'DSA',
        topicGroup: 'Hashmap',
        isCoreCS: true,
        lessonType: 'practice',
        content: {
            description: "Given a pattern and a string s, find if s follows the same pattern.",
            problemStatement: [
                '## 290. Word Pattern',
                '',
                '**Difficulty:** Easy | **Topics:** Hash Table, String',
                '',
                'Given a `pattern` and a string `s`, find if `s` follows the same pattern.',
                '',
                'Here **follow** means a full match, such that there is a bijection between a letter in `pattern` and a **non-empty** word in `s`. Specifically:',
                '* Each letter in `pattern` maps to exactly one unique word in `s`.',
                '* Each unique word in `s` maps to exactly one letter in `pattern`.',
                '* No two letters map to the same word, and no two words map to the same letter.',
                '',
                '---',
                '',
                '### Example 1:',
                '```',
                'Input: pattern = "abba", s = "dog cat cat dog"',
                'Output: true',
                '```',
                '',
                '### Example 2:',
                '```',
                'Input: pattern = "abba", s = "dog cat cat fish"',
                'Output: false',
                '```',
                '',
                '### Example 3:',
                '```',
                'Input: pattern = "aaaa", s = "dog cat cat dog"',
                'Output: false',
                '```',
                '',
                '---',
                '',
                '### Constraints:',
                '* `1 <= pattern.length <= 300`',
                '* `pattern` contains only lower-case English letters.',
                '* `1 <= s.length <= 3000`',
                '* `s` contains only lowercase English letters and spaces ` `.',
                '* `s` does not contain any leading or trailing spaces.',
                '* All the words in `s` are separated by a single space.'
            ].join('\n'),
            starterCode: [
                '/**',
                ' * @param {string} pattern',
                ' * @param {string} s',
                ' * @return {boolean}',
                ' */',
                'var wordPattern = function(pattern, s) {',
                '    ',
                '};',
            ].join('\n'),
            testCases: [
                { input: '"abba", "dog cat cat dog"', expected: 'true', description: 'Standard match' },
                { input: '"abba", "dog cat cat fish"', expected: 'false', description: 'Mismatched word' },
                { input: '"aaaa", "dog cat cat dog"', expected: 'false', description: 'Pattern maps to different words' }
            ],
            tags: ['Hash Table', 'String']
        }
    },
    {
        title: '242. Valid Anagram',
        level: 'Beginner',
        difficulty: 'Easy',
        subject: 'DSA',
        topicGroup: 'Hashmap',
        isCoreCS: true,
        lessonType: 'practice',
        content: {
            description: "Given two strings s and t, return true if t is an anagram of s, and false otherwise.",
            problemStatement: [
                '## 242. Valid Anagram',
                '',
                '**Difficulty:** Easy | **Topics:** Hash Table, String, Sorting',
                '',
                'Given two strings `s` and `t`, return `true` if `t` is an **anagram** of `s`, and `false` otherwise.',
                '',
                '---',
                '',
                '### Example 1:',
                '```',
                'Input: s = "anagram", t = "nagaram"',
                'Output: true',
                '```',
                '',
                '### Example 2:',
                '```',
                'Input: s = "rat", t = "car"',
                'Output: false',
                '```',
                '',
                '---',
                '',
                '### Constraints:',
                '* `1 <= s.length, t.length <= 5 * 10^4`',
                '* `s` and `t` consist of lowercase English letters.'
            ].join('\n'),
            starterCode: [
                '/**',
                ' * @param {string} s',
                ' * @param {string} t',
                ' * @return {boolean}',
                ' */',
                'var isAnagram = function(s, t) {',
                '    ',
                '};',
            ].join('\n'),
            testCases: [
                { input: '"anagram", "nagaram"', expected: 'true', description: 'Valid anagram' },
                { input: '"rat", "car"', expected: 'false', description: 'Invalid anagram' },
                { input: '"a", "ab"', expected: 'false', description: 'Different lengths' }
            ],
            tags: ['Hash Table', 'String', 'Sorting']
        }
    },
    {
        title: '49. Group Anagrams',
        level: 'Intermediate',
        difficulty: 'Medium',
        subject: 'DSA',
        topicGroup: 'Hashmap',
        isCoreCS: true,
        lessonType: 'practice',
        content: {
            description: "Given an array of strings strs, group the anagrams together.",
            problemStatement: [
                '## 49. Group Anagrams',
                '',
                '**Difficulty:** Medium | **Topics:** Array, Hash Table, String, Sorting',
                '',
                'Given an array of strings `strs`, group **the anagrams** together. You can return the answer in **any order**.',
                '',
                '---',
                '',
                '### Example 1:',
                '```',
                'Input: strs = ["eat","tea","tan","ate","nat","bat"]',
                'Output: [["bat"],["nat","tan"],["ate","eat","tea"]]',
                '```',
                '',
                '### Example 2:',
                '```',
                'Input: strs = [""]',
                'Output: [[""]]',
                '```',
                '',
                '### Example 3:',
                '```',
                'Input: strs = ["a"]',
                'Output: [["a"]]',
                '```',
                '',
                '---',
                '',
                '### Constraints:',
                '* `1 <= strs.length <= 10^4`',
                '* `0 <= strs[i].length <= 100`',
                '* `strs[i]` consists of lowercase English letters.'
            ].join('\n'),
            starterCode: [
                '/**',
                ' * @param {string[]} strs',
                ' * @return {string[][]}',
                ' */',
                'var groupAnagrams = function(strs) {',
                '    ',
                '};',
            ].join('\n'),
            testCases: [
                { input: '["eat","tea","tan","ate","nat","bat"]', expected: '"[["bat"],["nat","tan"],["ate","eat","tea"]]"', description: 'Standard case' },
                { input: '[""]', expected: '"[[""]]"', description: 'Empty string' },
                { input: '["a"]', expected: '"[["a"]]"', description: 'Single character' }
            ],
            tags: ['Array', 'Hash Table', 'String', 'Sorting']
        }
    },
    {
        title: '202. Happy Number',
        level: 'Beginner',
        difficulty: 'Easy',
        subject: 'DSA',
        topicGroup: 'Hashmap',
        isCoreCS: true,
        lessonType: 'practice',
        content: {
            description: "Write an algorithm to determine if a number n is happy.",
            problemStatement: [
                '## 202. Happy Number',
                '',
                '**Difficulty:** Easy | **Topics:** Hash Table, Math, Two Pointers',
                '',
                'Write an algorithm to determine if a number `n` is **happy**.',
                '',
                'A **happy number** is a number defined by the following process:',
                '* Starting with any positive integer, replace the number by the sum of the squares of its digits.',
                '* Repeat the process until the number equals 1 (where it will stay), or it **loops endlessly in a cycle** which does not include 1.',
                '* Those numbers for which this process **ends in 1** are happy.',
                '',
                'Return `true` if `n` is a happy number, and `false` if not.',
                '',
                '---',
                '',
                '### Example 1:',
                '```',
                'Input: n = 19',
                'Output: true',
                'Explanation:',
                '1^2 + 9^2 = 82',
                '8^2 + 2^2 = 68',
                '6^2 + 8^2 = 100',
                '1^2 + 0^2 + 0^2 = 1',
                '```',
                '',
                '### Example 2:',
                '```',
                'Input: n = 2',
                'Output: false',
                '```',
                '',
                '---',
                '',
                '### Constraints:',
                '* `1 <= n <= 2^31 - 1`'
            ].join('\n'),
            starterCode: [
                '/**',
                ' * @param {number} n',
                ' * @return {boolean}',
                ' */',
                'var isHappy = function(n) {',
                '    ',
                '};',
            ].join('\n'),
            testCases: [
                { input: '19', expected: 'true', description: 'Happy number' },
                { input: '2', expected: 'false', description: 'Not a happy number' },
                { input: '1', expected: 'true', description: 'Base case' }
            ],
            tags: ['Hash Table', 'Math', 'Two Pointers']
        }
    },
    {
        title: '219. Contains Duplicate II',
        level: 'Beginner',
        difficulty: 'Easy',
        subject: 'DSA',
        topicGroup: 'Hashmap',
        isCoreCS: true,
        lessonType: 'practice',
        content: {
            description: "Find if there are two distinct indices i and j such that nums[i] == nums[j] and abs(i - j) <= k.",
            problemStatement: [
                '## 219. Contains Duplicate II',
                '',
                '**Difficulty:** Easy | **Topics:** Array, Hash Table, Sliding Window',
                '',
                'Given an integer array `nums` and an integer `k`, return `true` if there are two **distinct indices** `i` and `j` in the array such that `nums[i] == nums[j]` and `abs(i - j) <= k`.',
                '',
                '---',
                '',
                '### Example 1:',
                '```',
                'Input: nums = [1,2,3,1], k = 3',
                'Output: true',
                '```',
                '',
                '### Example 2:',
                '```',
                'Input: nums = [1,0,1,1], k = 1',
                'Output: true',
                '```',
                '',
                '### Example 3:',
                '```',
                'Input: nums = [1,2,3,1,2,3], k = 2',
                'Output: false',
                '```',
                '',
                '---',
                '',
                '### Constraints:',
                '* `1 <= nums.length <= 10^5`',
                '* `-10^9 <= nums[i] <= 10^9`',
                '* `0 <= k <= 10^5`'
            ].join('\n'),
            starterCode: [
                '/**',
                ' * @param {number[]} nums',
                ' * @param {number} k',
                ' * @return {boolean}',
                ' */',
                'var containsNearbyDuplicate = function(nums, k) {',
                '    ',
                '};',
            ].join('\n'),
            testCases: [
                { input: '"[1,2,3,1]", 3', expected: 'true', description: 'Duplicates within distance' },
                { input: '"[1,0,1,1]", 1', expected: 'true', description: 'Adjacent duplicates' },
                { input: '"[1,2,3,1,2,3]", 2', expected: 'false', description: 'No duplicates within distance' }
            ],
            tags: ['Array', 'Hash Table', 'Sliding Window']
        }
    },
    {
        title: '128. Longest Consecutive Sequence',
        level: 'Intermediate',
        difficulty: 'Medium',
        subject: 'DSA',
        topicGroup: 'Hashmap',
        isCoreCS: true,
        lessonType: 'practice',
        content: {
            description: "Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.",
            problemStatement: [
                '## 128. Longest Consecutive Sequence',
                '',
                '**Difficulty:** Medium | **Topics:** Array, Hash Table, Union-Find',
                '',
                'Given an unsorted array of integers `nums`, return the length of the longest consecutive elements sequence.',
                '',
                'You must write an algorithm that runs in **O(n)** time.',
                '',
                '---',
                '',
                '### Example 1:',
                '```',
                'Input: nums = [100,4,200,1,3,2]',
                'Output: 4',
                'Explanation: The longest consecutive elements sequence is [1, 2, 3, 4]. Therefore its length is 4.',
                '```',
                '',
                '### Example 2:',
                '```',
                'Input: nums = [0,3,7,2,5,8,4,6,0,1]',
                'Output: 9',
                '```',
                '',
                '### Example 3:',
                '```',
                'Input: nums = [1,0,1,2]',
                'Output: 3',
                '```',
                '',
                '---',
                '',
                '### Constraints:',
                '* `0 <= nums.length <= 10^5`',
                '* `-10^9 <= nums[i] <= 10^9`'
            ].join('\n'),
            starterCode: [
                '/**',
                ' * @param {number[]} nums',
                ' * @return {number}',
                ' */',
                'var longestConsecutive = function(nums) {',
                '    ',
                '};',
            ].join('\n'),
            testCases: [
                { input: '"[100,4,200,1,3,2]"', expected: '4', description: 'Standard case' },
                { input: '"[0,3,7,2,5,8,4,6,0,1]"', expected: '9', description: 'Longer sequence with duplicates inside' },
                { input: '"[]"', expected: '0', description: 'Empty array' }
            ],
            tags: ['Array', 'Hash Table', 'Union-Find']
        }
    }
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
    console.log('Connected to MongoDB');
    for (const problem of problems) {
        const existing = await Topic.findOne({ title: problem.title, subject: 'DSA' });
        if (existing) {
            await Topic.findByIdAndUpdate(existing._id, problem);
            console.log('Updated:', problem.title);
        } else {
            await new Topic(problem).save();
            console.log('Added:', problem.title);
        }
    }
    mongoose.connection.close();
}).catch(e => { console.error(e); process.exit(1); });
